### ISSUE TITLE
Await inside Do method

### ISSUE THREAD

**Issue by cesarmm** [sergeyzwezdin/monads.net#10]
Hello
 I can't use await word inside a Do method. I found problems to work with the asynchronous model asyn/await.
Ex.1, call await inside Do:
myCollectionOfVars.Do(myVar =>{
//... do my stuffs
var answer = await my_awaitable_method(myVar.Id);
});

Ex. 2, use of Do in awaitable result:
await my_awaitable_method_return_a_collection(DateTime.Now)
.Do(myVar => {
// do stuff
});

Is it possible? Thanks.

**Comment by sergeyzwezdin** [comment]
Hi @cesarmm 
Monads does not support asyncs for the moment. 
I plan to update it this autumn where in particular add async/await support.
Thanks for your patient.

**Comment by cesarmm** [comment]
Hi sergey,
your answer sounds good. I'm addicted to monads.net and I'm glad to know that it isn't a dead project. :)

**Comment by sergeyzwezdin** [comment]
Sorry. Project is deprecated for the moment.
