### ISSUE TITLE
IEnumeratable Do is impossible to use

### ISSUE THREAD

**Issue by arteny** [sergeyzwezdin/monads.net#13]
I can't use any IEnumeratable<> Do in sense of foreach, beacause such error occurs:
Error   96  The call is ambiguous between the following methods or properties: 'System.Monads.MaybeIEnumerable.Do<Service.Models.FinalResult>(System.Collections.Generic.IEnumerable<Service.Models.FinalResult>, System.Action<Service.Models.FinalResult>)' and 'System.Monads.MaybeObjects.Do<System.Collections.Generic.IEnumerable<Service.Models.FinalResult>>(System.Collections.Generic.IEnumerable<Service.Models.FinalResult>, System.Action<System.Collections.Generic.IEnumerable<Service.Models.FinalResult>>)'

**Comment by sergeyzwezdin** [comment]
Sorry. Project is deprecated for the moment.
